import { Decimal, toDecimal, formatCurrency } from './decimal';
import type { CalculationOutcome, CalculationStep } from './outcome';
import { createErrorOutcome } from './outcome';

export interface RoiInput {
  initialInvestment: number | string;
  finalValue: number | string;
  investmentPeriodYears?: number | string;
  currencySymbol?: string;
}

export interface RoiResult {
  netProfit: number;
  roiPercentage: number;
  annualizedRoiPercentage?: number;
  formattedNetProfit: string;
  formattedRoiPercentage: string;
  formattedAnnualizedRoi: string;
}

export const ROI_FORMULA_ID = 'formula-finance-roi-v1.0.0';
export const ROI_FORMULA_VERSION = '1.0.0';

export function calculateRoi(input: RoiInput): CalculationOutcome<RoiResult> {
  const initial = toDecimal(input.initialInvestment);
  const finalVal = toDecimal(input.finalValue);
  const years = input.investmentPeriodYears !== undefined && input.investmentPeriodYears !== ''
    ? toDecimal(input.investmentPeriodYears)
    : undefined;
  const symbol = input.currencySymbol || '$';

  if (!initial || initial.lte(0)) {
    return createErrorOutcome(ROI_FORMULA_ID, ROI_FORMULA_VERSION, 'Initial investment must be greater than zero.', { initialInvestment: input.initialInvestment });
  }
  if (!finalVal || finalVal.lt(0)) {
    return createErrorOutcome(ROI_FORMULA_ID, ROI_FORMULA_VERSION, 'Final value cannot be negative.', { finalValue: input.finalValue });
  }
  if (years && (years.lte(0) || years.gt(100))) {
    return createErrorOutcome(ROI_FORMULA_ID, ROI_FORMULA_VERSION, 'Investment period must be between 0 and 100 years.', { investmentPeriodYears: input.investmentPeriodYears });
  }

  const trace: CalculationStep[] = [];
  const netProfit = finalVal.minus(initial).toDecimalPlaces(2, Decimal.ROUND_HALF_UP);
  const roiPct = netProfit.div(initial).times(100).toDecimalPlaces(2, Decimal.ROUND_HALF_UP);

  trace.push({
    stepNumber: 1,
    label: 'Compute Net Profit / Return',
    expression: `${formatCurrency(finalVal, symbol)} final - ${formatCurrency(initial, symbol)} initial`,
    result: formatCurrency(netProfit, symbol),
    explanation: 'Total capital gain or loss generated by the investment.',
  });

  trace.push({
    stepNumber: 2,
    label: 'Compute Total ROI Percentage',
    expression: `(${formatCurrency(netProfit, symbol)} ÷ ${formatCurrency(initial, symbol)}) × 100%`,
    result: `${roiPct.toFixed(2)}%`,
    explanation: 'Percentage gain or loss relative to the original capital basis.',
  });

  let annualizedRoi: Decimal | undefined;
  let formattedAnnualized = 'N/A';

  if (years && years.gt(0)) {
    // Annualized ROI = ((Final / Initial) ^ (1 / years) - 1) * 100
    const ratio = finalVal.div(initial).toNumber();
    if (ratio > 0) {
      const cagr = (Math.pow(ratio, 1 / years.toNumber()) - 1) * 100;
      annualizedRoi = new Decimal(cagr).toDecimalPlaces(2, Decimal.ROUND_HALF_UP);
      formattedAnnualized = `${annualizedRoi.toFixed(2)}% / yr`;

      trace.push({
        stepNumber: 3,
        label: 'Compute Annualized ROI (CAGR)',
        expression: `((${finalVal.toString()} ÷ ${initial.toString()})^(1 ÷ ${years.toString()}) - 1) × 100%`,
        result: formattedAnnualized,
        explanation: 'Compound annual growth rate normalized per year.',
      });
    }
  }

  return {
    status: 'success',
    value: {
      netProfit: netProfit.toNumber(),
      roiPercentage: roiPct.toNumber(),
      annualizedRoiPercentage: annualizedRoi ? annualizedRoi.toNumber() : undefined,
      formattedNetProfit: formatCurrency(netProfit, symbol),
      formattedRoiPercentage: `${roiPct.toFixed(2)}%`,
      formattedAnnualizedRoi: formattedAnnualized,
    },
    normalizedInputs: {
      initialInvestment: initial.toNumber(),
      finalValue: finalVal.toNumber(),
      investmentPeriodYears: years ? years.toNumber() : undefined,
    },
    appliedDefaults: [],
    formulaId: ROI_FORMULA_ID,
    formulaVersion: ROI_FORMULA_VERSION,
    trace,
    warnings: [],
    generatedAt: new Date().toISOString(),
  };
}
